name: Aggregate Markdown

on: [push]

jobs:
  aggregate_markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: grep -Ril '\.md$' dev-docs | xargs cat > aggregated.md
    - run: git add aggregated.md
    - run: git commit -m "Aggregate Markdown files"
    - run: git push
